# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/sf_tradeengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/sf_tradeengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_tradeengine/CMakeFiles /media/sf_tradeengine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_tradeengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trader

# Build rule for target.
trader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trader
.PHONY : trader

# fast build rule for target.
trader/fast:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/build
.PHONY : trader/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/net/SocketPoolTaskRunner.o: src/net/SocketPoolTaskRunner.cpp.o

.PHONY : src/net/SocketPoolTaskRunner.o

# target to build an object file
src/net/SocketPoolTaskRunner.cpp.o:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/SocketPoolTaskRunner.cpp.o
.PHONY : src/net/SocketPoolTaskRunner.cpp.o

src/net/SocketPoolTaskRunner.i: src/net/SocketPoolTaskRunner.cpp.i

.PHONY : src/net/SocketPoolTaskRunner.i

# target to preprocess a source file
src/net/SocketPoolTaskRunner.cpp.i:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/SocketPoolTaskRunner.cpp.i
.PHONY : src/net/SocketPoolTaskRunner.cpp.i

src/net/SocketPoolTaskRunner.s: src/net/SocketPoolTaskRunner.cpp.s

.PHONY : src/net/SocketPoolTaskRunner.s

# target to generate assembly for a file
src/net/SocketPoolTaskRunner.cpp.s:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/SocketPoolTaskRunner.cpp.s
.PHONY : src/net/SocketPoolTaskRunner.cpp.s

src/net/sockets/DataGramSocket.o: src/net/sockets/DataGramSocket.cpp.o

.PHONY : src/net/sockets/DataGramSocket.o

# target to build an object file
src/net/sockets/DataGramSocket.cpp.o:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/DataGramSocket.cpp.o
.PHONY : src/net/sockets/DataGramSocket.cpp.o

src/net/sockets/DataGramSocket.i: src/net/sockets/DataGramSocket.cpp.i

.PHONY : src/net/sockets/DataGramSocket.i

# target to preprocess a source file
src/net/sockets/DataGramSocket.cpp.i:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/DataGramSocket.cpp.i
.PHONY : src/net/sockets/DataGramSocket.cpp.i

src/net/sockets/DataGramSocket.s: src/net/sockets/DataGramSocket.cpp.s

.PHONY : src/net/sockets/DataGramSocket.s

# target to generate assembly for a file
src/net/sockets/DataGramSocket.cpp.s:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/DataGramSocket.cpp.s
.PHONY : src/net/sockets/DataGramSocket.cpp.s

src/net/sockets/EventSocket.o: src/net/sockets/EventSocket.cpp.o

.PHONY : src/net/sockets/EventSocket.o

# target to build an object file
src/net/sockets/EventSocket.cpp.o:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/EventSocket.cpp.o
.PHONY : src/net/sockets/EventSocket.cpp.o

src/net/sockets/EventSocket.i: src/net/sockets/EventSocket.cpp.i

.PHONY : src/net/sockets/EventSocket.i

# target to preprocess a source file
src/net/sockets/EventSocket.cpp.i:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/EventSocket.cpp.i
.PHONY : src/net/sockets/EventSocket.cpp.i

src/net/sockets/EventSocket.s: src/net/sockets/EventSocket.cpp.s

.PHONY : src/net/sockets/EventSocket.s

# target to generate assembly for a file
src/net/sockets/EventSocket.cpp.s:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/EventSocket.cpp.s
.PHONY : src/net/sockets/EventSocket.cpp.s

src/net/sockets/UDPSocket.o: src/net/sockets/UDPSocket.cpp.o

.PHONY : src/net/sockets/UDPSocket.o

# target to build an object file
src/net/sockets/UDPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/UDPSocket.cpp.o
.PHONY : src/net/sockets/UDPSocket.cpp.o

src/net/sockets/UDPSocket.i: src/net/sockets/UDPSocket.cpp.i

.PHONY : src/net/sockets/UDPSocket.i

# target to preprocess a source file
src/net/sockets/UDPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/UDPSocket.cpp.i
.PHONY : src/net/sockets/UDPSocket.cpp.i

src/net/sockets/UDPSocket.s: src/net/sockets/UDPSocket.cpp.s

.PHONY : src/net/sockets/UDPSocket.s

# target to generate assembly for a file
src/net/sockets/UDPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/trader.dir/build.make CMakeFiles/trader.dir/src/net/sockets/UDPSocket.cpp.s
.PHONY : src/net/sockets/UDPSocket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... trader"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/SocketPoolTaskRunner.o"
	@echo "... src/net/SocketPoolTaskRunner.i"
	@echo "... src/net/SocketPoolTaskRunner.s"
	@echo "... src/net/sockets/DataGramSocket.o"
	@echo "... src/net/sockets/DataGramSocket.i"
	@echo "... src/net/sockets/DataGramSocket.s"
	@echo "... src/net/sockets/EventSocket.o"
	@echo "... src/net/sockets/EventSocket.i"
	@echo "... src/net/sockets/EventSocket.s"
	@echo "... src/net/sockets/UDPSocket.o"
	@echo "... src/net/sockets/UDPSocket.i"
	@echo "... src/net/sockets/UDPSocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

